-- AlterEnum
ALTER TYPE "XPSource" ADD VALUE 'LESSON_COMPLETION';
ALTER TYPE "XPSource" ADD VALUE 'QUIZ_PASS';
ALTER TYPE "XPSource" ADD VALUE 'CERT_TIER';
ALTER TYPE "XPSource" ADD VALUE 'SKILL_UNLOCK';
ALTER TYPE "XPSource" ADD VALUE 'MISSION_COMPLETION';
ALTER TYPE "XPSource" ADD VALUE 'STREAK_BONUS';

-- CreateEnum
CREATE TYPE "ProgressionMissionTier" AS ENUM ('MICRO', 'STANDARD', 'MILESTONE', 'MAJOR');

-- AlterTable
ALTER TABLE "Lesson" ADD COLUMN "xpValue" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "Lesson" ADD COLUMN "exerciseXpBonus" INTEGER NOT NULL DEFAULT 10;

ALTER TABLE "Quiz" ADD COLUMN "passXp" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Quiz" ADD COLUMN "perfectXpBonus" INTEGER NOT NULL DEFAULT 25;

ALTER TABLE "ProgressionMission" ADD COLUMN "tier" "ProgressionMissionTier" NOT NULL DEFAULT 'STANDARD';

ALTER TABLE "ProgressionCertTier" ADD COLUMN "xpAward" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ProgressionSkill" ADD COLUMN "xpAward" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ProgressionSettings" ADD COLUMN "streak3Xp" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE "ProgressionSettings" ADD COLUMN "streak7Xp" INTEGER NOT NULL DEFAULT 75;
ALTER TABLE "ProgressionSettings" ADD COLUMN "streak30Xp" INTEGER NOT NULL DEFAULT 300;
ALTER TABLE "ProgressionSettings" ADD COLUMN "microDailyCap" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "ProgressionSettings" ADD COLUMN "standardDailyCap" INTEGER NOT NULL DEFAULT 100;

UPDATE "Course" SET "xpReward" = 100 WHERE "xpReward" < 100;

CREATE INDEX "XPEvent_userId_source_refId_idx" ON "XPEvent"("userId", "source", "refId");
